DROP DATABASE IF EXISTS crimes;

CREATE SCHEMA crimes;

CREATE TABLE crimes.crime
(
  id INT(10) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  victim_id INT(10) UNSIGNED COMMENT 'Person ID',
  criminal_id INT(10) UNSIGNED COMMENT 'Person ID',
  crime_type VARCHAR(255) NOT NULL,
  crime_level TINYINT(1) UNSIGNED DEFAULT 0 NOT NULL,
  crime_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX crime_id_uindex ON crimes.crime (id);
